"""Generate the static site using only the Python standard library."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parents[1]
DIMENSIONS = json.loads((ROOT/'scripts/image-dimensions.json').read_text())
ARROW = '<span class="arrow" aria-hidden="true">↗</span>'
LEGAL = 'From the beginning the AAMA-CDC has been a stand-alone entity with independent governance and financial responsibility. The AAMA-CDC is not affiliated with AAMA, Inc.'
NAV = [('Home','home.htm'),('About Us','aboutus.htm'),('Project Development','index.html#projects'),('News','news.htm'),('Contact Us','contactus.htm')]

def link(url, label, cls='text-link'):
    return f'<a class="{cls}" href="{url}">{label}{ARROW}</a>'

def image(src, alt, cls='', eager=False):
    width, height = DIMENSIONS[src]
    return f'<img src="{src}" alt="{escape(alt)}" class="{cls}" width="{width}" height="{height}" {"fetchpriority=high" if eager else "loading=lazy"} decoding="async">'

def contact_band():
    return f'<section class="wrap contact-band"><div><h2>Good communities start with a conversation.</h2><p>Connect with Peter Clementi about AAMA-CDC, our development work, or opportunities to work together.</p></div>{link("contactus.htm","Contact Us","button")}</section>'

def layout(title, desc, content, active='', home=False):
    nav=''.join(f'<a href="{url}" {"aria-current=page" if active == label else ""} {"class=button" if label == "Contact Us" else ""}>{label}</a>' for label,url in NAV)
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | AAMA-CDC</title><meta name="description" content="{escape(desc, quote=True)}">
<link rel="icon" href="images/intrologo1.gif" type="image/gif"><meta name="theme-color" content="#3156ad"><meta property="og:title" content="{escape(title, quote=True)} | AAMA-CDC"><meta property="og:description" content="{escape(desc, quote=True)}"><meta property="og:type" content="website">
<link rel="preload" href="assets/fonts/manrope-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="assets/site.css"><noscript><style>@media(max-width:960px){{.site-header{{height:auto}}.header-inner{{flex-wrap:wrap;padding-block:12px}}.nav{{display:flex;position:static;width:100%;border:0;padding:0}}.menu-toggle{{display:none}}}}</style></noscript><script src="assets/site.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="wrap header-inner">
<a class="brand" href="index.html" aria-label="AAMA-CDC Community Development Corporation home"><span class="brand-mark"><img src="images/aamacdchder.gif" alt="" width="700" height="120"></span><span class="brand-name">AAMA-CDC<small>Community Development Corporation</small></span></a>
<button type="button" class="menu-toggle" aria-controls="primary-navigation" aria-expanded="false">Menu</button><nav class="nav" id="primary-navigation" aria-label="Main navigation">{nav}</nav></div></header>
<main id="main">{content}</main><footer class="site-footer"><div class="wrap"><div class="footer-top"><div><a class="footer-name" href="index.html">AAMA-CDC</a><p>Building our community one brick at a time.</p><p>AAMA Community Development Corporation, Inc.</p></div><nav class="footer-links" aria-label="Footer navigation"><a href="aboutus.htm">About Us</a><a href="staff.htm">Staff</a><a href="aamacdclinks.htm">Links</a><a href="contactus.htm">Contact Us</a></nav></div><div class="footer-bottom"><span>Copyright © 2026 AAMA-CDC. All rights reserved.</span><span>AAMA-CDC is not affiliated with AAMA, Inc.</span></div></div></footer></body></html>'''

def intro(title, description, parent=''):
    crumb = f'<span>/</span><a href="index.html#projects">Project Development</a>' if parent else ''
    return f'<div class="wrap"><div class="page-intro"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.html">Home</a>{crumb}<span>/</span><span>{title}</span></nav><h1>{title}</h1><p>{description}</p></div></div>'

def write(name, title, desc, content, active=''):
    (ROOT/name).write_text(layout(title,desc,content,active),encoding='utf-8')

home=f'''
<section class="wrap hero"><div class="hero-copy"><p class="eyebrow">Rooted in community since 1988</p><h1>Building community.<br><span>Creating opportunity.</span></h1><p>Housing, economic development, and community revitalization for Houston’s Hispanic community and beyond.</p>{link('#projects','Explore our projects','button')}</div><figure class="hero-photo">{image('images/newsflash2.jpg','The brick apartment buildings and landscaped entrance at Plaza De Magnolia',eager=True)}<figcaption>Plaza De Magnolia, Houston’s East End</figcaption></figure></section>
<section class="wrap intro-line" aria-label="Our foundation"><div><strong>1988</strong><span>Established to serve<br>our community</span></div><div><strong>Houston</strong><span>Rooted in the East End<br>with a reach across South Texas</span></div><div><strong>501(c)(3)</strong><span>Founded as an independent<br>nonprofit corporation</span></div></section>
<section class="wrap section mission"><h2>A place to live.<br>A chance to grow.</h2><div class="mission-copy"><p>Strong neighborhoods begin with opportunity. AAMA-CDC was founded to address unmet needs in housing, economic development, and community revitalization.</p><p>Our work connects community needs with the development experience and partnerships to help meet them.</p><div class="mission-links">{link('aboutus.htm','About Us')}{link('earlyyears.htm','Our early years')}</div></div></section>
<section class="projects-section section" id="projects"><div class="wrap"><div class="section-header"><h2>Places with a purpose.</h2><p>Explore the housing and community developments that have shaped our work in Houston and South Texas.</p></div><div class="project-grid">
<a class="project-card" href="PlazaDeMagnolia.htm"><div class="image-frame">{image('images/newsflash2.jpg','Plaza De Magnolia apartments and entrance')}</div><div class="project-meta">Houston’s East End · Affordable housing</div><div class="project-title"><h3>Plaza De Magnolia</h3>{ARROW}</div><p>An 84-home development created to bring affordable housing to families in the Magnolia neighborhood.</p></a>
<a class="project-card" href="concord.htm"><div class="image-frame">{image('images/newsflash1.jpg','The entrance and apartment buildings at Concord at Allendale')}</div><div class="project-meta">Houston · Multifamily housing</div><div class="project-title"><h3>Concord at Allendale</h3>{ARROW}</div><p>A 264-home development that expanded our commitment to quality, affordable housing.</p></a></div>
<div class="more-projects"><a href="lasvillasdemagnolia.htm"><span>Las Villas De Magnolia<small>Houston’s East End · Senior housing initiative</small></span>{ARROW}</a><a href="valleycenter.htm"><span>Valley Center<small>Edinburg · Community services facility</small></span>{ARROW}</a></div></div></section>
<section class="wrap section community"><div class="community-image">{image('TAC/images/Dscf9318a.jpg','Community visitors touring Concord at Allendale in 2004')}{image('TAC/images/Dscf9322a.jpg','Neighbors and visitors meeting during the 2004 community development tour')}</div><div class="community-copy"><p class="eyebrow">More than buildings</p><h2 style="margin-top:18px">Community is at the heart of our work.</h2><p>From neighborhood gatherings to community development tours, our history is a story of people coming together around a shared future.</p>{link('news.htm','News')}</div></section>{contact_band()}'''
write('index.html','Community development in Houston','Housing, economic development, and community revitalization. Discover AAMA-CDC’s history, projects, and contact Peter Clementi.',home,'Home')
(ROOT/'home.htm').write_text((ROOT/'index.html').read_text(),encoding='utf-8')

about=intro('Built around community.','AAMA Community Development Corporation was formed in 1988 to address the Hispanic community’s unmet needs in housing, economic development, and community revitalization.')
about+=f'''<section class="wrap detail-layout"><div class="prose"><h2>Our mission</h2><p>Our mission and purpose is to develop neighborhood initiatives that provide housing opportunities, economic development opportunities, and community revitalization efforts, primarily in Houston’s East End.</p><h2>A foundation in the East End</h2><p>In 1993, the CDC began its operations in earnest with the initial Low-Income Housing Tax Credit project, Plaza De Magnolia. In 1998, new initiatives expanded our presence into South Texas and other Hispanic communities.</p><p>Our development history includes affordable multifamily housing, a community services facility in Edinburg, business development assistance, and educational facilities.</p>{link('earlyyears.htm','Our early years')}<h2>Independent from the beginning</h2><p>The CDC was chartered as an approved State of Texas non-profit corporation, with IRS-approved 501(c)(3) status.</p><p>{LEGAL}</p></div><figure>{image('images/newsflash2.jpg','Plaza De Magnolia, an early AAMA-CDC housing development')}<figcaption>Plaza De Magnolia in Houston’s East End.</figcaption></figure></section>{contact_band()}'''
write('aboutus.htm','About Us','Learn about AAMA-CDC’s mission, history, and independent community development work.',about,'About Us')

projects=[
('PlazaDeMagnolia.htm','Plaza De Magnolia','Affordable housing in Houston’s East End.','images/newsflash2.jpg','Plaza De Magnolia apartment buildings', [('Homes','84'),('First occupancy','1996')],'<p>AAMA-CDC developed Plaza De Magnolia in 1995, with occupancy beginning in 1996. The project used Low-Income Housing Tax Credits to provide homes for lower-income families.</p><p>The original project was designed for families whose incomes did not exceed 60% of the Houston area median income. AAMA-CDC structured the development as managing partner, with the National Equity Fund and other tax-credit investors as limited partners.</p><h2>A neighborhood gathering place</h2><p>Plaza De Magnolia also hosted community events, including National Night Out in August 2004.</p>', '7310 Sherman &amp; 74th Street<br>Houston, Texas 77011'),
('concord.htm','Concord at Allendale','Expanding affordable housing opportunities in Houston.','images/newsflash1.jpg','Concord at Allendale apartment buildings and entrance', [('Homes','264'),('Ribbon cutting','2003')],'<p>Concord at Allendale was developed as a joint venture between AAMA-CDC and Trammel Crow Residential. The development included one- and two-bedroom apartments with rents designed to be within reach of families at the 60% income limit.</p><p>The original development used tax-exempt bonds for permanent financing. Its ribbon cutting took place on December 17, 2003.</p><h2>Opening the doors</h2><p>In March 2004, the property welcomed visitors for a Texas Association community development tour.</p>'+link('tactour.htm','View the community tour')+'<p><a class="text-link" href="b768.wmv" download>Download the original video (WMV)</a></p>','4800 Allendale<br>Houston, Texas 77017'),
('lasvillasdemagnolia.htm','Las Villas De Magnolia','A senior housing initiative in Houston’s Magnolia neighborhood.','images/mvillas011.jpg','The original Las Villas De Magnolia development site',[('Proposed homes','116'),('Original site','3.5 acres')],'<p>AAMA-CDC acquired a 3.5-acre parcel at Harrisburg and 72nd Streets in Houston’s East End as the proposed site for a 116-unit senior residential center.</p><p>The original plans emphasized the neighborhood’s amenities and the need for senior housing. In January 2004, a public meeting brought future neighbors together to discuss the development.</p><p>This page documents the original proposal. It does not indicate current construction status or housing availability.</p>'+link('Public%20Meeting.htm','View the public meeting'),'Harrisburg &amp; 72nd Streets<br>Houston, Texas'),
('valleycenter.htm','Valley Center','A home for community services in the Rio Grande Valley.','images/valleycenter1_02.jpg','Original Valley Center photographs showing its interior and exterior',[('Facility','21,000 sq. ft.'),('Acquired','2000')],'<p>AAMA-CDC acquired Valley Center in Edinburg, Texas, in 2000. The former commercial office building was adapted for a social service agency under a long-term lease.</p><p>The facility supported the delivery of prevention and recovery programs and youth outreach services to communities in the Rio Grande Valley.</p><p>The original facility included space for temporary residence, large meeting rooms, adjoining offices, and parking.</p>','Edinburg, Texas')]
for slug,title,desc,src,alt,facts,body,address in projects:
    detail=intro(title,desc,True)+f'<section class="wrap detail-layout"><div class="prose"><dl class="facts">'+''.join(f'<div><dt>{k}</dt><dd>{v}</dd></div>' for k,v in facts)+f'</dl>{body}<h2>Location</h2><p>{address}</p><p class="archive-note">Project history from AAMA-CDC’s original site. For current information, please contact Peter Clementi.</p></div><figure>{image(src,alt,eager=True)}<figcaption>Photography from the AAMA-CDC project archive.</figcaption></figure></section>'+contact_band()
    write(slug,title,desc,detail,'Project Development')

profile=intro('People behind the purpose.','Development experience. A commitment to community.')+f'''<section class="wrap profile">{image('images/photo128.jpg','Peter Clementi')}<div><h2>Peter Clementi</h2><p class="role">Member &amp; primary contact</p><p>Peter brings experience in housing development, construction, and financial services to AAMA-CDC’s community development work.</p><p>His background includes homebuilding in Houston’s West University and Montrose neighborhoods, as well as project management for educational and residential facilities.</p><p>Contact Peter for information about AAMA-CDC and its projects.</p>{link('contactus.htm','Contact Us','button')}</div></section>'''
write('staff.htm','Staff','Meet Peter Clementi, AAMA-CDC member and primary contact.',profile)
write('clementi.htm','Peter Clementi','Peter Clementi’s community development experience and contact information.',profile)
contact=intro('Contact Us','Connect with Peter Clementi about our organization, project history, and community development opportunities.')+f'''<section class="wrap contact-layout"><div class="contact-person">{image('images/photo128.jpg','Peter Clementi')}<div><h2>Peter Clementi</h2><p>Member &amp; primary contact</p>{link('mailto:pclementi@aamacdc.org','pclementi@aamacdc.org')}<br>{link('clementi.htm','About Peter')}</div></div><div class="contact-info"><h2>AAMA Community Development Corp.</h2><address>4600 Gulf Freeway, Suite M170<br>Houston, TX 77023</address><p><a href="tel:+17139235433">(713) 923-5433</a></p><p>Fax: (713) 923-5494</p></div></section>'''
write('contactus.htm','Contact Us','Contact Peter Clementi at pclementi@aamacdc.org or reach AAMA-CDC at (713) 923-5433.',contact,'Contact Us')

history=[('Business Literacy Houston','A City of Houston-funded program, jointly administered with the Urban Business Initiative of Houston, that offered business development assistance to small inner-city businesses.'),('Educational facilities, 1999-2000','Development and funding support for Building C-2 for AAMA, Inc., including a proposal to Harris County Community Development and project and contract administration.'),('Multipurpose Education Center, 1997-2000','Support for the development of a 31,000-square-foot education facility, including securing bank financing, assembling the development team, and working with the project architect.'),('Building improvements, 1995-1997','Project management for fire code, health, and safety improvements to existing educational buildings.'),('Harrisburg-Wayside revitalization, 1993-1994','A two-year partnership with Houston’s East End Chamber of Commerce to provide training and technical assistance to area businesses, funded by the City of Houston.')]
write('earlyyears.htm','Early Years','A look back at AAMA-CDC’s completed early development programs.',intro('Our early years.','The projects and programs that helped establish our development experience. These programs are closed and are presented as history.')+'<section class="wrap history-grid">'+''.join(f'<article><h2>{h}</h2><p>{p}</p></article>' for h,p in history)+'</section>','About Us')

news=[('NationalNightOut.htm','August 3, 2004','National Night Out at Plaza De Magnolia','Neighbors came together for an evening focused on community relationships and crime prevention.'),('tactour.htm','March 11, 2004','A community development tour','Visitors toured Concord at Allendale with the Texas Association of Community Development Corporations.'),('Public%20Meeting.htm','January 2004','Planning for Las Villas De Magnolia','A public meeting invited future neighbors to discuss the proposed senior housing development.'),('newsflash.htm','December 17, 2003','Welcoming Concord at Allendale','A ribbon cutting marked the opening of a 264-home affordable housing development.')]
write('news.htm','News','Community events and development milestones from the AAMA-CDC archive.',intro('Our community, through the years.','News and events from the AAMA-CDC archive. These stories document our history and are not upcoming events.')+'<section class="wrap article-list">'+''.join(f'<a class="article-row" href="{u}"><time>{d}</time><div><h2>{h}</h2><p>{p}</p></div>{ARROW}</a>' for u,d,h,p in news)+'</section>','News')
write('NationalNightOut.htm','National Night Out','An August 2004 community gathering at Plaza De Magnolia.',intro('National Night Out.','August 3, 2004 · Community archive')+'<section class="wrap"><div class="prose"><p>Plaza De Magnolia hosted its annual National Night Out, bringing neighbors together to build relationships and support crime prevention.</p><p>The original event collage below captures an evening with residents and neighbors.</p><p><a class="text-link" href="cleaner256modif.wmv" download>Download the original event video (WMV)</a></p></div><figure class="archive-image" style="margin-top:30px">'+image('images/National-Night-Out.jpg','Original collage of residents, activities, and neighborhood gatherings at National Night Out in 2004')+'</figure></section>','News')
gallery=''.join(image(f'TAC/images/Dscf{n}a.jpg','Visitors at the March 2004 Concord at Allendale community development tour') for n in ['9315','9316','9318','9320','9322','9325','9328','9330','9332','9336','9340','9359'])
write('tactour.htm','Community Development Tour','Photographs of the March 11, 2004 community development tour at Concord at Allendale.',intro('A closer look at community development.','March 11, 2004 · Concord at Allendale')+'<section class="wrap"><div class="prose"><p>The Texas Association community development tour brought visitors to Concord at Allendale to see the development and meet with the community.</p></div><div class="gallery">'+gallery+'</div></section>','News')
write('Public Meeting.htm','Las Villas Public Meeting','A January 2004 neighborhood meeting about the proposed Las Villas De Magnolia development.',intro('A conversation with future neighbors.','January 2004 · Las Villas De Magnolia')+'<section class="wrap"><div class="prose"><p>AAMA-CDC hosted a public meeting over coffee to discuss plans for a proposed 116-unit senior housing development at Harrisburg and 72nd Streets.</p><p><a class="text-link" href="magnolia.wmv" download>Download the original meeting video (WMV)</a></p></div><div class="gallery">'+''.join(image('images/'+f,'Neighbors discussing the original Las Villas De Magnolia proposal') for f in ['mDscf1529.jpg','mDscf1533.jpg','mDscf1536.jpg'])+'</div></section>','News')
write('newsflash.htm','Concord Ribbon Cutting','The December 2003 ribbon cutting at Concord at Allendale.',intro('Welcoming Concord at Allendale.','December 17, 2003 · Community archive')+'<section class="wrap detail-layout"><div class="prose"><p>AAMA-CDC celebrated the ribbon cutting for Concord at Allendale, a 264-home affordable housing development created in partnership with Trammel Crow Residential.</p><p>The initiative was designed to help families access attractive housing while lowering their housing costs.</p>'+link('concord.htm','Explore Concord at Allendale')+'</div><figure>'+image('TAC/images/Dscf9359a.jpg','Balloons at the entrance of Concord at Allendale')+'</figure></section>','News')

# Preserve the original resource destinations and labels, grouped for readability.
# These are historical partnerships, not claims about current affiliations.
import re
original_links = ROOT/'scripts'/'original-links.txt'
if not original_links.exists():
    source=(ROOT/'aamacdclinks.htm').read_text(encoding='latin1')
    items=[]
    for url,label in re.findall(r'<a\s+href="(https?://[^\"]+)"[^>]*>(.*?)</a>',source,re.S|re.I):
        label=' '.join(re.sub('<[^>]+>',' ',label).split())
        if label: items.append((url,label))
    original_links.write_text('\n'.join(url+'\t'+label for url,label in items),encoding='utf-8')
items=[line.split('\t',1) for line in original_links.read_text().splitlines() if '\t' in line and not line.startswith('http://al-fin.com/')]
resources=intro('Links','Financial, community, and development organizations referenced in our original project history.')+'<section class="wrap"><p class="archive-note">This directory preserves historical partner references. Organizations and web addresses may have changed since the original projects.</p><div class="resource-list">'
for label,start,end in [('Financial partners',0,6),('Community partners',6,11),('Development partners',11,len(items))]:
    unlinked = {'Community partners': '<p>La Rosa of Houston</p>', 'Development partners': '<p>Whitney Management/Whitney Capital</p>'}.get(label, '')
    resources+=f'<div><h2>{label}</h2>'+''.join(f'<p><a href="{escape(u,quote=True)}">{l}</a></p>' for u,l in items[start:end])+unlinked+'</div>'
resources+='</div></section>'
write('aamacdclinks.htm','Links','Historical financial, community, and development partner resources.',resources)

def redirect(name, target):
    path=ROOT/name
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url={target}"><title>AAMA-CDC</title></head><body><p>This page has moved. <a href="{target}">Continue to AAMA-CDC</a>.</p></body></html>\n',encoding='utf-8')

# Retire the board and former individual profiles, including direct bookmarked URLs.
redirects={'board.htm':'staff.htm','board518.htm':'staff.htm','santos.htm':'staff.htm','gary.htm':'staff.htm','carlosalvarez.htm':'staff.htm','intro.htm':'index.html','tactour2.htm':'tactour.htm','mediaISDN.htm':'concord.htm','mediamed.htm':'concord.htm','medialarge.htm':'concord.htm','mediaplazademagniteout.htm':'NationalNightOut.htm','nclrphoenix/nclrphoenix.htm':'../news.htm'}
for name,target in redirects.items(): redirect(name,target)
# Old public backup URLs must not reintroduce retired member or board information.
for folder in ['backup','bak','tmp']:
    for path in (ROOT/folder).glob('*'):
        if path.suffix.lower() in ['.htm','.html']:
            target=redirects.get(path.name,path.name)
            if not (ROOT/target).exists(): target='index.html'
            redirect(str(path.relative_to(ROOT)),'../'+target.replace(' ','%20'))
print('Generated modern pages and legacy redirects.')
